# Description: SDK for Beaglebone distribution
# URL: http://www.buildgear.org

name=beaglebone-sdk
version=1.0
release=1
depends=(native/crosstool-ng fs)
options=(nostrip)

build() {
   mkdir $PKG/$name

   # Copy fully populated sysroot
   cp -a $SYSROOT/* $PKG/$name

   # Cleanup
   rm -rf $PKG/$name/share/locale
   rm -rf $PKG/$name/$HOST/sysroot/usr/{sbin,bin,man,share,etc}
   rm -rf $PKG/$name/$HOST/sysroot/{lib/modules,var,media,mnt,opt,proc,root,run,bin,sbin,srv,sys,tmp,home,etc}

   # Create tarball
   tar -C $PKG -acpf $OUTPUT/beaglebone-sdk.tar.gz .
}
